name: bookstore

services:
  auth:
    image: bookstore.auth
    build:
      context: .
      dockerfile: Dockerfile.auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/.microsoft/usersecrets:ro
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1536m

  store:
    image: bookstore.store
    build:
      context: .
      dockerfile: Dockerfile.store
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/.microsoft/usersecrets:ro
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1536m